"""Initial migration

Revision ID: 7ac08e2cd2b9
Revises: 
Create Date: 2026-01-13 20:01:57.073979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac08e2cd2b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('telegram_payment_charge_id', sa.String(), nullable=True),
    sa.Column('stars_amount', sa.Integer(), nullable=False),
    sa.Column('tons_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_used', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('telegram_payment_charge_id')
    )
    op.create_table('donations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('stars_amount', sa.Integer(), nullable=False),
    sa.Column('tons_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('week_key', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_week_key'), 'donations', ['week_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_week_key'), table_name='donations')
    op.drop_table('donations')
    op.drop_table('payments')
    # ### end Alembic commands ###

